---
output: github_document
---





<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


<h2 dir="rtl>

## Tidy_Friday

</h2>

<p dir="rtl>

 سوف نقوم في كل يوم جمعة بإضافة جدول بيانات جديد، سوف نحاول ان تكون البيانات عن المملكة العربية السعودية بقدر الإمكان.

ليس هناك اي متطلبات لطريقة تحليل البيانات ، حيث يمكنك بناء نموذج او إنشاء رسم بياني او كتابة تقرير اوعمل ماتريد.

اذا كنا لديك اي سؤال او تحتاج الى مساعدة فنحن نرحب بك في مجتمعنا 
`R4DS Online Learning Community Saudi`
على
[`slack`](https://join.slack.com/t/r4dssa/shared_invite/zt-fyg8b592-7L7PFhbOt8AM0oWDWZjYfg
)

</p>

<h2 dir="rtl>

## R4DS Online Learning Community Saudi

</h2>

<p dir="rtl>

ملهمين بمجتمع 
`R4DS Online Learning Community` 
قمنا بإنشاء 
`R4DS Online Learning Community Saudi` 

حيث نهدف الى نتبادل الخبرات والاستشارات عن تحليل البيانات بإستخدام 
`R` 
غالبا سوف نستخدم المكتبات التي قام بتطويرها فريق 
[`Rstudio`](https://rstudio.com/)
وهي 
[`Tidyverse`](https://www.tidyverse.org/)
[`Tidumodels`](https://www.tidymodels.org/)
[`Shiny`](https://shiny.rstudio.com/)
وغيرها من المكتبات التي تتبع
`Tidyverse Ecosystem`


<!-- badges: start -->
<!-- badges: end -->

</p>

<h2 dir="rtl>

## مصادر نرشحها لتعلم R

</h2>

<p dir="rtl>

احد أهم المصادر هو 
[Rstudio Education](https://education.rstudio.com)

كما يمكنك البحث عن الكتب المجانية المتعلقة ب 
R
[هنا](https://bookdown.org/home/tags/)

هنا تجد مجموعة من الكتب مفتوحة المصدر بالإضافة الى بعض التسجيلات علي يوتيوب

</p>

<h3 dir="rtl>

### مدخل الى تعلم R

</h3>

<p dir="rtl>

1- [R4ds](https://r4ds.had.co.nz) (يعد هذا الكتاب اهم مصدر لتعلم R)

2- [R Cookbook](https://rc2e.com)

3- [Hadly`s Recordings on YouTube](https://www.youtube.com/watch?v=go5Au01Jrvs)

</p>

<h3 dir="rtl>

### تصوير البيانات

</h3>

<p dir="rtl>

1- [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org)

2- [The R Graph Gallery](https://www.r-graph-gallery.com)

3- [Fundamentals of Data Visualization](https://serialmentor.com/dataviz/) 

4- [Thomas Recordings on YouTube](https://www.youtube.com/watch?v=h29g21z0a68&t=7028s)

5- [Data Visualization with R](https://rkabacoff.github.io/datavis/)

</p>

<h3 dir="rtl>

### إحصاء

</h3>


<p dir="rtl>

1- [Statistical Inference via Data Science](https://moderndive.com)


</p>


<h3 dir="rtl>

### Rmarkdown

</h3>

<p dir="rtl>

1- [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)

2- [Rmarkdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/)

</p>

<h3 dir="rtl>

### بناء النماذج

</h3>


<p dir="rtl>


1- [Feature Engineering and Selection: A Practical Approach for Predictive Models](http://www.feat.engineering)

2- [The Elements of Statistical Learning: Data Mining, Inference, and Prediction](https://web.stanford.edu/~hastie/ElemStatLearn/)

3- [An Introduction to Statistical Learning: with Applications in R](https://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf)

4- [tidymodels](https://www.tidymodels.org/learn/)



</p>


<h3 dir="rtl>

### تحليل النصوص

</h3>

<p dir="rtl>


1- [Text Mining](https://www.tidymodels.org/books/tidytext/)


</p>

<h3 dir="rtl>

### مصادر اخرى

</h3>


<p dir="rtl>


1- [Rweekly](https://rweekly.org)


2- [David Robinson`s YouTube channel](https://www.youtube.com/user/safe4democracy)


3- [Julia Silge`s YouTube channe](https://www.youtube.com/channel/UCTTBgWyJl2HrrhQOOc710kA)


4- [دروس مجانية](https://education.rstudio.com/blog/2020/05/remote-roundup/)

</p>


